language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - export DJANGO_SETTINGS_MODULE=teracy.html5boilerplate.test_settings
install:
  - pip install -e .
  - pip install -r requirements/test.txt
before_script:
  - flake8 teracy
script:
  - coverage run --branch --source=teracy `which django-admin.py` test teracy.html5boilerplate
  - coverage report --omit=teracy/html5boilerplate/test*

